import 'package:flutter/material.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';

const SaveIcon = FontAwesomeIcons.solidSave;
const SupportIcon = FontAwesomeIcons.solidComments;
const DashboardIcon = FontAwesomeIcons.chartLine;
const ContractsIcon = FontAwesomeIcons.fileAlt;
const SettingsIcon = FontAwesomeIcons.cogs;
const LogoutIcon = FontAwesomeIcons.signOutAlt;
const DeleteIcon = FontAwesomeIcons.trashAlt;
const AttachmentIcon = FontAwesomeIcons.paperclip;
const RedoIcon = FontAwesomeIcons.redoAlt;
const UndoIcon = FontAwesomeIcons.undoAlt;
const CameraIcon = FontAwesomeIcons.camera;
const ImagesIcon = FontAwesomeIcons.images;
const AddIcon = Icons.add;
const PlusIcon = AddIcon;
const MinusIcon = FontAwesomeIcons.minus;
const RemoveIcon = MinusIcon;
const CheckIcon = FontAwesomeIcons.check;
const CheckDoubleIcon = FontAwesomeIcons.checkDouble;
const CheckSquareIcon = FontAwesomeIcons.checkSquare;
const SquareIcon = FontAwesomeIcons.square;
const EmailIcon = Icons.email;
const LockIcon = Icons.lock;
const ChevronDownIcon = FontAwesomeIcons.chevronDown;
const ChevronUpIcon = FontAwesomeIcons.chevronUp;
const ChevronLeftIcon = FontAwesomeIcons.chevronLeft;
const ChevronRightIcon = FontAwesomeIcons.chevronRight;
const CloseIcon = FontAwesomeIcons.times;
const ShareIcon = FontAwesomeIcons.shareAlt;
const CopyIcon = FontAwesomeIcons.copy;
const EditIcon = FontAwesomeIcons.pen;
const UserIcon = FontAwesomeIcons.userAlt;
const SendIcon = FontAwesomeIcons.solidPaperPlane;
const EllipsisVIcon = FontAwesomeIcons.ellipsisV;
const EllipsisHIcon = FontAwesomeIcons.ellipsisH;
const ArrowDownIcon = FontAwesomeIcons.arrowDown;
const ArrowUpIcon = FontAwesomeIcons.arrowUp;
const ArrowLeftIcon = FontAwesomeIcons.arrowLeft;
const ArrowRightIcon = FontAwesomeIcons.arrowRight;
const ArchiveIcon = FontAwesomeIcons.archive;
const StarIcon = FontAwesomeIcons.star;
const StarHalfIcon = FontAwesomeIcons.starHalf;
const KeyIcon = FontAwesomeIcons.key;

const NotificationIcon = FontAwesomeIcons.bell;
const InformativeIcon = FontAwesomeIcons.tv;
const DevicesIcon = FontAwesomeIcons.hdd;
const WifiIcon = FontAwesomeIcons.wifi;
const AdvertisingIcon = FontAwesomeIcons.bullhorn;
const ClockIcon = FontAwesomeIcons.clock;

const EnvelopeOpenTextIcon = FontAwesomeIcons.envelopeOpenText;
const TextHeightIcon = FontAwesomeIcons.textHeight;
const ExclamationTriangleIcon = FontAwesomeIcons.exclamationTriangle;
const FolderOpenIcon = FontAwesomeIcons.folderOpen;

const NavigationBackIcon = Icons.arrow_back;
const SearchIcon = FontAwesomeIcons.search;

const SMSIcon = FontAwesomeIcons.sms;
const PhoneIcon = FontAwesomeIcons.mobileAlt;
